---
- name: Setting repository EPEL to "{{ wtd_repo_epel_state }}"
  package:
    name: "{{ item }}"
    state: "{{ wtd_repo_epel_state }}"
  become: yes
  with_items:
    - "{{ wtd_repo_epel_packages }}"
